/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modul5;

 

 
/**
 *
 * @author PC RPL - R1
 */
public class tugas extends javax.swing.JFrame {

    /**
     * Creates new form tugas
     */
    public tugas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lNAMA = new javax.swing.JLabel();
        lALAMAT = new javax.swing.JLabel();
        lMAKANAN = new javax.swing.JLabel();
        lMINUMAN = new javax.swing.JLabel();
        eNAMA = new javax.swing.JTextField();
        eALAMAT = new javax.swing.JTextField();
        cAyamGeprek = new javax.swing.JCheckBox();
        cNasiGoreng = new javax.swing.JCheckBox();
        cSotoAyam = new javax.swing.JCheckBox();
        cJusBuah = new javax.swing.JCheckBox();
        cCoffe = new javax.swing.JCheckBox();
        cLemonTea = new javax.swing.JCheckBox();
        bPesan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lNAMA.setText("NAMA");

        lALAMAT.setText("ALAMAT");

        lMAKANAN.setText("MAKANAN");

        lMINUMAN.setText("MINUMAN");

        cAyamGeprek.setText("Ayam Geprek");

        cNasiGoreng.setText("Nasi Goreng");

        cSotoAyam.setText("Soto Ayam");

        cJusBuah.setText("Jus Buah");

        cCoffe.setText("Coffe");

        cLemonTea.setText("Lemon Tea");

        bPesan.setText("PESAN");
        bPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPesanActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lNAMA)
                            .addComponent(lALAMAT)
                            .addComponent(lMAKANAN)
                            .addComponent(lMINUMAN))
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cSotoAyam)
                            .addComponent(cAyamGeprek)
                            .addComponent(cNasiGoreng)
                            .addComponent(cJusBuah)
                            .addComponent(cCoffe)
                            .addComponent(cLemonTea)
                            .addComponent(eNAMA, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(eALAMAT))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bPesan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNAMA)
                    .addComponent(eNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lALAMAT)
                    .addComponent(eALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lMAKANAN)
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cAyamGeprek)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cNasiGoreng)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cSotoAyam)
                        .addGap(11, 11, 11)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lMINUMAN)
                    .addComponent(cJusBuah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cCoffe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cLemonTea)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bPesan)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPesanActionPerformed
       
    String nama = lNAMA.getText();
    String alamat = lALAMAT.getText();

    // Membuat string untuk daftar pesanan
    String pesanan = "Pesanan dari: " + nama + "\nAlamat: " + alamat + "\n\nPesanan:\n";
 
    // Mengecek pilihan makanan
    if (cAyamGeprek.isSelected()) {
        pesanan += "- " + cAyamGeprek.getText() + "\n";
    }
    if (cNasiGoreng.isSelected()) {
        pesanan += "- " + cNasiGoreng.getText() + "\n";
    }
    if (cSotoAyam.isSelected()) {
        pesanan += "- " + cSotoAyam.getText() + "\n";
    }
    // Tambahkan checkbox makanan lainnya jika ada

    // Mengecek pilihan minuman
    if (cJusBuah.isSelected()) {
        pesanan += "- " + cJusBuah.getText() + "\n";
    }
    if (cCoffe.isSelected()) {
        pesanan += "- " + cCoffe.getText() + "\n";
    }
    if (cLemonTea.isSelected()) {
        pesanan += "- " + cLemonTea.getText() + "\n";
    }
    // Tambahkan checkbox minuman lainnya jika ada

    // Menampilkan pesanan di TextArea
    jTextArea1.setText(pesanan);
    }//GEN-LAST:event_bPesanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bPesan;
    private javax.swing.JCheckBox cAyamGeprek;
    private javax.swing.JCheckBox cCoffe;
    private javax.swing.JCheckBox cJusBuah;
    private javax.swing.JCheckBox cLemonTea;
    private javax.swing.JCheckBox cNasiGoreng;
    private javax.swing.JCheckBox cSotoAyam;
    private javax.swing.JTextField eALAMAT;
    private javax.swing.JTextField eNAMA;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lALAMAT;
    private javax.swing.JLabel lMAKANAN;
    private javax.swing.JLabel lMINUMAN;
    private javax.swing.JLabel lNAMA;
    // End of variables declaration//GEN-END:variables
}
